server {
    listen 80;
    server_name localhost;

    root /usr/share/nginx/html;
    index login.html index.html;

    # Gzip Compression
    gzip on;
    gzip_types text/plain text/css application/json application/javascript text/xml application/xml application/xml+rss text/javascript;

    # Phuc vu static assets
    location / {
        try_files $uri $uri/ /login.html;
    }

    error_page 500 502 503 504 /50x.html;
    location = /50x.html {
        root /usr/share/nginx/html;
    }
}
